version: '3'

services:
  kiteai-bot:
    build: .
    volumes:
      - ./accounts.txt:/app/accounts.txt
      - ./config.json:/app/config.json
      - ./agents.json:/app/agents.json
    restart: unless-stopped

networks:
  kite-network:
    driver: bridge 