version: '3.8'

services:
  kite-ai-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kite-ai-bot
    volumes:
      - ./wallets.txt:/app/wallets.txt
      - ./proxies.txt:/app/proxies.txt
    environment:
      - NODE_ENV=production
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - kite-network

networks:
  kite-network:
    driver: bridge 