version: '3'

services:
  kiteai-bot:
    build: .
    command: python bot-anti.py
    volumes:
      - ./accounts.txt:/app/accounts.txt
      - ./proxy.txt:/app/proxy.txt
      - ./agents.json:/app/agents.json
      - ./captcha_key.txt:/app/captcha_key.txt
      - ./telegram.json:/app/telegram.json
    restart: unless-stopped
    environment:
      - AUTO_INPUT=1

networks:
  kite-network:
    driver: bridge 